from tkinter import *
root=Tk()
topframe=Frame(root)
topframe.pack()
bottomframe=Frame(root)
bottomframe.pack(side=BOTTOM)
root.geometry("344x233")
label=Label(root,text="hello",fg="red",bg="cyan")
label.pack()
btn=Button(topframe,text="file",fg="blue",bg="gray")
btn1=Button(topframe,text="edit",fg="blue",bg="gray")
btn2=Button(topframe,text="view",fg="blue",bg="gray")
btn3=Button(topframe,text="navigate",fg="blue",bg="gray")
btn.pack(side=LEFT)
btn1.pack(side=LEFT)
btn2.pack(side=LEFT)
btn3.pack(side=LEFT)

root.mainloop()
